config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :sessions

  resources :posts , except: [:edit, :update, :destroy] do
  resources :comments, only: :create
  end
  resources :users , except: [:edit, :update, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/gif.rb
class Gif < ActiveRecord::Base
    belongs_to :users
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  def date_published
     created_at.localtime.strftime("%A, %B %-d, %Y at %l:%M %p")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :videos
  has_many :gifs
  has_many :posts
  #attr_reader :password

  def password=(unencrypted_password)
    unless unencrypted_password.empty?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def authenticate(unencrypted_password)
    if BCrypt::Password.new(self.password_digest) == unencrypted_password
      return self
    else
      return false
    end
  end
  validates :email, presence: true, uniqueness: true
end

app/models/video.rb
class Video < ActiveRecord::Base
    belongs_to :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  private
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
       post = Post.find(params[:post_id])
       comment = post.comments.create(comment_params)
       comment.user = current_user
       comment.save
       redirect_to post_path(comment.post)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id if current_user
    if @post.save
      redirect_to '/posts'
    else
      render 'new'
    end

  end

  private
  def post_params
    params.require(:post).permit(:title, :media_url, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
      @user = User.find_by(email: params[:email])
      if @user && @user.authenticate(params[:password])
          #set a cookie so our browser knows we are who we say we are
          session[:user_id] = @user.id.to_s
          redirect_to users_path
      else
          #give them another shot at loggin in
          #redirect_to "/"
      end
  end

   def destroy
     session[:user_id] = nil
    redirect_to root_url, notice: "logged out!"
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/login'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to '/'
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      session[:user_id] = nil
      redirect_to '/'
    else
      render 'show'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_name, :email, :password)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/gifs/create.html.erb
<h1>Gifs#create</h1>
<p>Find me in app/views/gifs/create.html.erb</p>

app/views/gifs/destroy.html.erb
<h1>Gifs#destroy</h1>
<p>Find me in app/views/gifs/destroy.html.erb</p>

app/views/gifs/index.html.erb
<h1>Gifs#index</h1>
<p>Find me in app/views/gifs/index.html.erb</p>

app/views/gifs/new.html.erb
<h1>Gifs#new</h1>
<p>Find me in app/views/gifs/new.html.erb</p>

app/views/gifs/show.html.erb
<h1>Gifs#show</h1>
<p>Find me in app/views/gifs/show.html.erb</p>

app/views/gifs/update.html.erb
<h1>Gifs#update</h1>
<p>Find me in app/views/gifs/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">MediaHub</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-center">
          <li> <% if current_user %>
            <li>Welcome, <%= current_user.user_name %>!</li>
            <li><a href="/posts/new">Create a New Post</a></li>
            <li><a href="/posts">View Posts</a>

          <% end %></li>

          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/">Home</a></li>
              <% if current_user %>
              <li><%= link_to 'Edit Account Information', edit_user_path(current_user) %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <% if current_user %>
                <li><%= link_to 'Logout', sessions_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Login", login_path, method: :get %><li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<%= yield %>

</body>
</html>

app/views/posts/_form_post.html.erb
<%= bootstrap_form_for(@post, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-4") do |f| %>
  <% if @post.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @post.errors.full_messages %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "Title of Post" %>
  </div>
  <div class="field">
    <%= f.label :media_url %>
    <%= f.text_area :media_url, placeholder: "Media url MUST be a link to a YouTube video or GIF" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="row">
  <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6">
    <div class="thumbnail">
      <div class="caption">
        <h3><%= post.title %></h3>
        <p><%= link_to post.media_url, post.media_url %></p>
        <p><%= post.created_at %></p>
        <p>Submitted by: <strong><% if post.user %>
                <%= post.user.user_name %>
                <%else %>
                Anonymous User
                <%end%></strong></p>

        <p><%= link_to "Go to Post", post_path(post), class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>
</div>
<%end%>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6">
    <div class="thumbnail">
      <div class="caption">
  <h3>Add a New Post</h3>
</div>
<%= render 'form_post' %>
</div>
</div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6">
      <div class="thumbnail">
        <div class="caption">
          <%= form_for [@post, Comment.new] do |f| %>
            <%= f.label :body, "New comment:", class: "form-control" %>
            <%= f.text_area :body, class: "col-sm-2 control-label", class: "form-control", placeholder: "Add a new comment here" %>
            <%= f.submit "Add your comment!", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6">
      <div class="thumbnail">
        <div class="caption">
          <h1><%= @post.title %><small> <%= @post.date_published %> </small></h1>
          <p><%= link_to @post.media_url, @post.media_url %></p>
          <% @post.comments.each do |comment| %>
          <ul class="list-group-item">
            <p>User: <strong><% if comment.user %>
                    <%= comment.user.user_name %>
                    <%else %>
                    Anonymous User
                    <%end%></strong><p>
            <ul><%= comment.body %></ul>
          </ul>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6">
      <div class="thumbnail">
        <div class="caption">
          <h1>Edit Your Account Information</h1>
          <p>Enter your new information below</p>

          <%= form_for @user, :html => {:class => "form-horizontal center"} do |f| %>
            <% if @user.errors.any? %>
              <div class="error_messages">
                <h2>Form is invalid</h2>
                <ul>
                  <% for message in @user.errors.full_messages %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="form-group">
              <%= f.label :first_name, "First name:", class: "col-md-4 control-label" %>
              <div class="col-md-4">
              <%= f.text_field :first_name, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :last_name, "Last name:", class: "col-md-4 control-label" %>
              <div class="col-md-4">
                <%= f.text_field :last_name, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :email, "Email:", class: "col-md-4 control-label" %>
              <div class="col-md-4">
                <%= f.email_field :email, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :password, "Password:", class: "col-md-4 control-label" %>
              <div class="col-md-4">
                <%= f.password_field :password, class: "form-control" %><br><%= f.submit "Update", class: "btn btn-default"%><button type="submit" class="btn btn-danger"><%= link_to 'Destroy', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %> </button>
              </div>
            </div>
          <% end %>
          </form>
        </div>
      </div>
    </div>
  </div>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>MediaHub Homepage</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">

    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="inner cover">
            <h1 class="cover-heading">MediaHub</h1>
            <h2 class="cover-subheading">All of your favorite Youtube videos and GIFs on one site!</h2>
            <p class="lead">Create an account and link to the video of your choosing.<br>Compile and share the best entertainment the internet has to offer!</p>
            <p class="lead">
              <a href="/users/new" class="btn btn-lg btn-info">Learn more</a>
            </p>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<div class="row">
  <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6">
    <div class="thumbnail">
      <div class="caption">
  <% if current_user %>
    <br><br><br><br><br><br><br><br><br><br>
    <h2>You already have an Account</h2>
    <h2><a href="/posts">Click here to view the posts</a></h2>
  <% else %>
    <h1>Signing Up is Easier than ever!</h1>
    <p>Enter your information below</p>
    <%= bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-4") do |f| %>
      <%= f.text_field :first_name %>
      <%= f.text_field :last_name %>
      <%= f.email_field :email %>
      <%= f.text_field :user_name %>
      <%= f.password_field :password %>
      <%= f.form_group do %>
        <%= f.submit "Create New Account" %>
      <% end %>
    <% end %>
  <% end %>
</div>
</div>
</div>
</div>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= @user.inspect %>

app/views/videos/destroy.html.erb
<h1>Videos#destroy</h1>
<p>Find me in app/views/videos/destroy.html.erb</p>

app/views/videos/index.html.erb
<h1>Videos#index</h1>
<p>Find me in app/views/videos/index.html.erb</p>

app/views/videos/new.html.erb
<h1>Videos#new</h1>
<p>Find me in app/views/videos/new.html.erb</p>

app/views/videos/show.html.erb
<h1>Videos#show</h1>
<p>Find me in app/views/videos/show.html.erb</p>

app/views/videos/update.html.erb
<h1>Videos#update</h1>
<p>Find me in app/views/videos/update.html.erb</p>